version: '3.5'
services:
  unit:
    build: .
    depends_on:
      - kafka
      - schema-registry
    networks: [unit]
  kafka:
    image: 'confluentinc/cp-kafka:5.0.0'
    depends_on: [zookeeper]
    expose: [9092]
    networks: [unit]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
  schema-registry:
    image: 'confluentinc/cp-schema-registry:5.0.0'
    depends_on: [kafka]
    expose: [8081]
    networks: [unit]
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.0.0'
    expose: ['2181']
    networks:
      - unit
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
networks:
  unit:
    name: cruby-unit-2